wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    user: x:x # Run as the same user as the wordpress image to avoid permission issues
    entrypoint: >
      /bin/sh -c "
      # 1. Wait for MySQL to be ready
      until wp db check --allow-root; do
        echo 'Waiting for database...'
        sleep 3
      done

      # 2. Check if WP is already installed
      if ! wp core is-installed --allow-root; then
        echo 'Installing WordPress...'
        wp core install \
          --url=http://104.211.55.92 \
          --title='My WordPress Site' \
          --admin_user=admin \
          --admin_password=admin123 \
          --admin_email=admin@gmail.com \
          --skip-email \
          --allow-root
        
        echo 'WordPress installation complete.'
      else
        echo 'WordPress is already installed. Skipping.'
      fi
      "
