  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      MYSQL_CLIENT_FLAGS: "--ssl-mode=DISABLED"
    command: >
      sh -c "
      until wp db check --allow-root --skip-ssl; do
        echo 'Waiting for database...';
        sleep 5;
      done &&
      if ! wp core is-installed --allow-root; then
        wp core install \
          --url=http://104.211.55.89 \
          --title='My WordPress Site' \
          --admin_user=admin \
          --admin_password=admin123 \
          --admin_email=admin@gmail.com \
          --skip-email \
          --allow-root;
      fi
      "
